import type { App, TFile } from "obsidian";
import { ROOT_ID } from "./types";
import { splitFrontmatter } from "./stash-package";

/** OKF (Open Knowledge Format) — Phase 2: the complementary frontmatter model +
 *  the template + the per-folder rebuild. See docs/branches/okf.md.
 *
 *  Design: COMPLEMENTARY, never subtractive. Stashpad keeps its id-based
 *  parent/parentLink/children untouched; OKF adds its own namespaced fields so a
 *  folder is browsable as OKF AND still a normal Stashpad folder:
 *   - `okfParent` / `okfChildren` — RELATIVE MARKDOWN links (OKF's cross-link
 *     style), Stashpad-managed (reserved; rebuilt here).
 *   - `okfType` / `okfTitle` / `okfTimestamp` — user-editable; filled with
 *     defaults only when missing. On EXPORT these map to OKF's bare spec keys
 *     (`type`/`title`/`timestamp`) — that mapping is Phase 4. */

export const OKF_DEFAULT_TEMPLATE_PATH = "OKF Template.md";
/** Seed template: `okfType` is a user-editable default; {{body}} is where the
 *  composed note body lands. okfParent/okfChildren/okfTitle/okfTimestamp are
 *  filled by the rebuild, not the template (they're per-note/derived). */
export const OKF_TEMPLATE_BODY = "---\nokfType: concept\n---\n{{body}}\n";

/** Field legend embedded in each generated index.md so an LLM/agent reading the
 *  LIVE vault knows how Stashpad's namespaced fields map to OKF (we keep `okf*`
 *  live to avoid colliding with Obsidian's own `tags`/`title`; the bare spec keys
 *  are emitted on export). */
export const OKF_LEGEND = [
  "> Generated by Stashpad — this folder is an Open Knowledge Format (OKF) bundle.",
  "> Field legend: `okfType`→`type`, `okfTitle`→`title`, `okfDescription`→`description`, `okfTags`→`tags`, `okfTimestamp`→`timestamp`; `okfParent`/`okfChildren` are relative-markdown cross-links. Stashpad's own `id`/`parent` are extensions — ignore them for OKF.",
].join("\n");

/** Human/LLM-readable label for an OKF link (drop the -<id> filename suffix). */
export function okfTitleFromFile(file: TFile): string {
  return file.basename.replace(/-[a-z0-9]{4,12}$/, "").replace(/-/g, " ").trim() || file.basename;
}
/** A relative markdown link to a sibling note (Stashpad folders are flat, so the
 *  target is just the filename). Spaces %-encoded so the link is valid. */
function okfLink(file: TFile): string {
  return `[${okfTitleFromFile(file)}](${encodeURI(file.name)})`;
}

/** Create the OKF template note if it's missing; returns its vault path. */
export async function ensureOkfTemplate(app: App, path = OKF_DEFAULT_TEMPLATE_PATH): Promise<string> {
  try {
    if (!(await app.vault.adapter.exists(path))) await app.vault.create(path, OKF_TEMPLATE_BODY);
  } catch { /* raced / already exists — fine */ }
  return path;
}

/** Folders that "use OKF" = folders whose assigned note template IS the OKF
 *  template (template-driven enablement, per the user's design). */
export function okfFolders(noteTemplates: Record<string, string> | undefined, templatePath: string): string[] {
  if (!templatePath) return [];
  const tp = templatePath.replace(/^\/+/, "");
  return Object.entries(noteTemplates ?? {})
    .filter(([, v]) => (v ?? "").replace(/^\/+/, "") === tp)
    .map(([k]) => k.replace(/\/+$/, ""));
}

/** Write/refresh OKF frontmatter for every note directly in `folder`. Managed
 *  link fields (okfParent/okfChildren) are always reconciled; okfType/okfTitle/
 *  okfTimestamp are only filled when absent (user owns them after). Reads from
 *  DISK (cache lags after edits), skip-if-equal, paced writes. */
export async function rebuildOkfForFolder(app: App, folder: string): Promise<{ checked: number; written: number }> {
  const cleaned = folder.replace(/\/+$/, "");
  type E = { file: TFile; id: string; parent: string; modified: string; created: string };
  const byId = new Map<string, E>();
  const childrenByParent = new Map<string, string[]>();
  for (const f of app.vault.getMarkdownFiles()) {
    if ((f.parent?.path?.replace(/\/+$/, "") ?? "") !== cleaned) continue;
    let fm: Record<string, unknown>;
    try { fm = splitFrontmatter(await app.vault.read(f)).fm; } catch { continue; }
    const id = typeof fm.id === "string" ? fm.id : null;
    if (!id) continue;
    const parent = typeof fm.parent === "string" ? fm.parent : ROOT_ID;
    byId.set(id, { file: f, id, parent, modified: typeof fm.modified === "string" ? fm.modified : "", created: typeof fm.created === "string" ? fm.created : "" });
    const arr = childrenByParent.get(parent) ?? []; arr.push(id); childrenByParent.set(parent, arr);
  }

  let checked = 0, written = 0;
  for (const e of byId.values()) {
    if (e.id === ROOT_ID) continue; // the home note is represented by index.md (Phase 3)
    checked += 1;
    const parentLink = (e.parent && e.parent !== ROOT_ID && byId.get(e.parent)) ? okfLink(byId.get(e.parent)!.file) : null;
    const childLinks = (childrenByParent.get(e.id) ?? []).map((cid) => byId.get(cid)).filter((x): x is E => !!x).map((x) => okfLink(x.file));
    try {
      let changed = false;
      await app.fileManager.processFrontMatter(e.file, (m) => {
        // Managed relative-markdown links.
        if (parentLink) { if (m.okfParent !== parentLink) { m.okfParent = parentLink; changed = true; } }
        else if (m.okfParent !== undefined) { delete m.okfParent; changed = true; }
        const cur = Array.isArray(m.okfChildren) ? (m.okfChildren as unknown[]) : [];
        const eq = cur.length === childLinks.length && cur.every((v, i) => v === childLinks[i]);
        if (childLinks.length) { if (!eq) { m.okfChildren = childLinks; changed = true; } }
        else if (m.okfChildren !== undefined) { delete m.okfChildren; changed = true; }
        // User-editable defaults — only fill when missing.
        if (m.okfType === undefined) { m.okfType = "concept"; changed = true; }
        if (m.okfTitle === undefined) { m.okfTitle = okfTitleFromFile(e.file); changed = true; }
        if (m.okfTimestamp === undefined) { const ts = e.modified || e.created; if (ts) { m.okfTimestamp = ts; changed = true; } }
      });
      if (changed) { written += 1; await new Promise((r) => setTimeout(r, 50)); }
    } catch (err) { console.warn("[Stashpad] OKF rebuild failed", e.file.path, err); }
  }
  // Regenerate the folder's index.md (OKF requires a per-dir index).
  try { await app.vault.adapter.write(`${cleaned}/index.md`, await buildOkfIndex(app, cleaned)); }
  catch (err) { console.warn("[Stashpad] OKF index.md write failed", cleaned, err); }
  return { checked, written };
}

/** Build the OKF `index.md` for a folder: a `type: index` concept that lists every
 *  note (nested by hierarchy) with relative-markdown links, plus the field legend.
 *  `scopeIds` (optional) limits it to an exported subtree — index reflects the
 *  EXPORT scope, not the whole folder. NOTE: never reads/writes `.claude/INDEX.md`
 *  (that's Claude's code map) — this is a lowercase `index.md` in vault content. */
export async function buildOkfIndex(app: App, folder: string, scopeIds?: Set<string>): Promise<string> {
  const cleaned = folder.replace(/\/+$/, "");
  type N = { id: string; file: TFile; parent: string; title: string; type: string; position: number; created: string };
  const byId = new Map<string, N>();
  const kids = new Map<string, N[]>();
  for (const f of app.vault.getMarkdownFiles()) {
    if ((f.parent?.path?.replace(/\/+$/, "") ?? "") !== cleaned) continue;
    if (f.name === "index.md") continue; // never index the index
    let fm: Record<string, unknown>;
    try { fm = splitFrontmatter(await app.vault.read(f)).fm; } catch { continue; }
    const id = typeof fm.id === "string" ? fm.id : null;
    if (!id || id === ROOT_ID) continue;
    if (scopeIds && !scopeIds.has(id)) continue;
    byId.set(id, {
      id, file: f, parent: typeof fm.parent === "string" ? fm.parent : ROOT_ID,
      title: typeof fm.okfTitle === "string" && fm.okfTitle ? fm.okfTitle : okfTitleFromFile(f),
      type: typeof fm.okfType === "string" && fm.okfType ? fm.okfType : "concept",
      position: typeof fm.position === "number" ? fm.position : Number.MAX_SAFE_INTEGER,
      created: typeof fm.created === "string" ? fm.created : "",
    });
  }
  for (const n of byId.values()) { const a = kids.get(n.parent) ?? []; a.push(n); kids.set(n.parent, a); }
  for (const a of kids.values()) a.sort((x, y) => (x.position - y.position) || x.created.localeCompare(y.created));

  const lines: string[] = [];
  const walk = (n: N, depth: number, seen: Set<string>): void => {
    if (seen.has(n.id)) return; seen.add(n.id);
    lines.push(`${"  ".repeat(depth)}- [${n.title}](${encodeURI(n.file.name)}) — ${n.type}`);
    for (const c of kids.get(n.id) ?? []) walk(c, depth + 1, seen);
  };
  // Roots of the (possibly scoped) set: parent is ROOT or outside the set.
  const seen = new Set<string>();
  const roots = [...byId.values()].filter((n) => n.parent === ROOT_ID || !byId.has(n.parent))
    .sort((x, y) => (x.position - y.position) || x.created.localeCompare(y.created));
  for (const r of roots) walk(r, 0, seen);

  const folderName = cleaned.split("/").pop() || cleaned;
  return [
    "---", "type: index", `title: ${folderName} (OKF index)`, "---", "",
    `# ${folderName}`, "", OKF_LEGEND, "", "## Concepts",
    lines.length ? lines.join("\n") : "_No concepts yet._", "",
  ].join("\n");
}
